name: Release
on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.3'
          check-latest: true
          cache: true

      - name: Build
        # if: startsWith(github.ref, 'refs/tags/')
        run: make releases; ls -lh bin/

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*
          token: ${{ secrets.GITHUB_TOKEN }}
