name: Release
on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.3'
          check-latest: true
          cache: true

      - name: Build
        # if: startsWith(github.ref, 'refs/tags/')
        run: make releases; ls -lh bin/

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          files: bin/*
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
